# Generated by Django 4.0.4 on 2022-06-17 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Showing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=255)),
                ("date", models.CharField(max_length=255)),
                ("datetime", models.CharField(max_length=255)),
                ("format", models.CharField(max_length=255)),
                ("imdb_id", models.CharField(max_length=255)),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showings",
                        to="cinema.cinema",
                    ),
                ),
            ],
        ),
    ]
