from apps.cinehoyts.constants import CINEMA_ZONES as CINEHOYTS_CINEMA_ZONES
from apps.cinemark.constants import CINEMA_ZONES_TAGS as CINEMARK_CINEMA_ZONES_TAGS

CINEMAS_ZONES = CINEHOYTS_CINEMA_ZONES + CINEMARK_CINEMA_ZONES_TAGS
