# Generated by Django 4.0.4 on 2022-06-17 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zone', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('chain', models.CharField(choices=[('CineHoyts', 'CineHoyts'), ('Cinemark', 'Cinemark'), ('Cineplanet', 'Cineplanet'), ('Independent', 'Independent'), ('Muvix', 'Muvix')], max_length=255)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='cinema.town')),
            ],
        ),
    ]
